#include "mbed.h"
#include "bbcar.h"

Ticker servo_ticker;
PwmOut pin8(D8), pin9(D9);

BBCar car(pin8, pin9, servo_ticker);

int main() {
    // please contruct you own calibration table with each servo

    // for D8
    double pwm_table0[] = {-50, -40, -30, -20, -10, 0, 10, 20, 30, 40, 50};
    double speed_table0[] = {-25.440, -20.974, -15.551, -10.288, -4.785, 0, 0.799, 5.742, 11.484, 16.189, 20.177};
    
    // for D9
    double pwm_table1[] = {-150, -120, -90, -60, -30, 0, 30, 60, 90, 120, 150};
    double speed_table1[] = {-16.747, -16.349, -12.392, -12.521, -6.539, 0, 5.184, 11.404, 14.193, 16.269, 16.747};

    // first and fourth argument : length of table
    car.setCalibTable(11, pwm_table0, speed_table0, 11, pwm_table1, speed_table1);

    while (1) {
        // go with the speed 5cm/sec which is generated by the table!
        car.goStraightCalib(5);
        wait(5);
        car.stop();
        wait(5);
    }
}